#!/usr/bin/env bash
# host-setup.sh - Idempotent host setup for IIAB demo server
# Replaces: playbooks/01-host-setup.yml
# Usage: sudo bash host-setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-iiab.sh disable=SC1091
source "$SCRIPT_DIR/lib-iiab.sh"

echo "=== Setting up IIAB Demo Server Host ==="

# Ensure root
ensure_root "$@"

###############################################################################
# 1. Install required packages (idempotent)
###############################################################################
echo ""
echo "=== Installing required packages ==="

PACKAGES=(
    nginx
    systemd-container
    debootstrap
    parted
    jq
    e2fsprogs
    dosfstools
    psmisc
    nftables
    bridge-utils
    expect
    curl
    git
    certbot
    python3-certbot-nginx
)

# Check which packages are missing
MISSING=()
for pkg in "${PACKAGES[@]}"; do
    if ! dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
        MISSING+=("$pkg")
    fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
    echo "Installing: ${MISSING[*]}"
    apt-get update -qq
    apt-get install -y "${MISSING[@]}"
else
    echo "All packages already installed"
fi

###############################################################################
# 2. Enable and start systemd services (idempotent)
###############################################################################
echo ""
echo "=== Enabling systemd services ==="

for svc in systemd-networkd systemd-resolved; do
    if systemctl is-active --quiet "$svc"; then
        echo "$svc is already running"
    else
        echo "Starting $svc..."
        systemctl enable --now "$svc"
    fi
done

###############################################################################
# 3. Enable IPv4 forwarding (idempotent)
###############################################################################
echo ""
echo "=== Configuring IPv4 forwarding ==="

if [ "$(cat /proc/sys/net/ipv4/ip_forward)" = "1" ]; then
    echo "IPv4 forwarding already enabled"
else
    echo "Enabling IPv4 forwarding..."
    sysctl -w net.ipv4.ip_forward=1
fi

# Make it persistent
if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf 2>/dev/null; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    echo "Made IPv4 forwarding persistent"
fi

###############################################################################
# 4. Create container bridge network (idempotent)
###############################################################################
setup_bridge

###############################################################################
# 5. Deploy nginx configuration (idempotent)
###############################################################################
echo ""
echo "=== Configuring nginx ==="

# Create directories
mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled /var/www/certbot

# Create a minimal nginx config (will be regenerated by nginx-gen.sh later)
NGINX_CONF="/etc/nginx/sites-available/iiab-demo.conf"
if [ ! -f "$NGINX_CONF" ]; then
    echo "Creating initial nginx config..."
    cat > "$NGINX_CONF" << 'EOF'
# Auto-generated by host-setup.sh
# This will be regenerated by democtl reload

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location / {
        return 404;
    }
}
EOF
else
    echo "Nginx config already exists"
fi

# Enable site (idempotent)
if [ ! -L "/etc/nginx/sites-enabled/iiab-demo.conf" ]; then
    echo "Enabling nginx site..."
    ln -sf /etc/nginx/sites-available/iiab-demo.conf /etc/nginx/sites-enabled/
else
    echo "Nginx site already enabled"
fi

# Remove default site (idempotent)
if [ -L "/etc/nginx/sites-enabled/default" ]; then
    echo "Removing default nginx site..."
    rm -f /etc/nginx/sites-enabled/default
else
    echo "Default nginx site already removed"
fi

# Enable and start nginx (idempotent)
if systemctl is-active --quiet nginx; then
    echo "nginx is already running"
else
    echo "Starting nginx..."
    systemctl enable --now nginx
fi

###############################################################################
# 6. Configure nftables for container NAT and isolation (idempotent)
###############################################################################
echo ""
echo "=== Configuring nftables for container NAT ==="

EXT_IF=$(ip route | grep default | awk '{print $5}' | head -n1)
if [ -z "$EXT_IF" ]; then
    echo "Warning: Could not detect external interface, skipping networking" >&2
else
    # Flush only IIAB-managed nftables tables (avoid destroying other firewall configs)
    echo "Flushing IIAB nftables tables..."
    nft delete table inet iiab 2>/dev/null || true
    nft delete table bridge iiab 2>/dev/null || true

    # Flush Docker's iptables FORWARD DROP policy so our containers can reach the internet
    if command -v iptables >/dev/null 2>&1; then
        echo "Resetting iptables FORWARD policy to ACCEPT..."
        iptables -P FORWARD ACCEPT 2>/dev/null || true
    fi

    echo "Firewall state cleared"

    if ! setup_nftables_nat "$EXT_IF"; then
        echo "ERROR: NAT setup failed, restoring safe FORWARD policy" >&2
        iptables -P FORWARD DROP 2>/dev/null || true
        exit 1
    fi

    if ! add_container_isolation; then
        echo "ERROR: Isolation rules setup failed, restoring safe FORWARD policy" >&2
        iptables -P FORWARD DROP 2>/dev/null || true
        exit 1
    fi
fi

# Make nftables persistent
mkdir -p /etc/nftables
nft list ruleset > /etc/nftables.conf.tmp && mv /etc/nftables.conf.tmp /etc/nftables.conf
echo "nftables rules saved to /etc/nftables.conf"

###############################################################################
# 7. Create required directories (idempotent)
###############################################################################
echo ""
echo "=== Creating required directories ==="

ensure_dirs /var/lib/machines /var/www/certbot

###############################################################################
# 8. Test nginx configuration
###############################################################################
echo ""
echo "=== Testing nginx configuration ==="

nginx_reload

echo ""
echo "=== Host setup complete! ==="
echo "Add demos with:"
echo "  make small medium large"
echo "  democtl add <name> --local-vars <path>"
