#!/usr/bin/env bash
# host-setup.sh - Idempotent host setup for IIAB demo server
# Replaces: playbooks/01-host-setup.yml
# Usage: sudo bash host-setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-iiab.sh disable=SC1091
source "$SCRIPT_DIR/lib-iiab.sh"

echo "=== Setting up IIAB Demo Server Host ==="

# Ensure root
ensure_root "$@"

###############################################################################
# 1. Install required packages (idempotent)
###############################################################################
echo ""
echo "=== Installing required packages ==="

PACKAGES=(
    nginx
    systemd-container
    debootstrap
    parted
    jq
    e2fsprogs
    dosfstools
    psmisc
    iptables
    bridge-utils
    expect
    curl
    git
    certbot
    python3-certbot-nginx
)

# Check which packages are missing
MISSING=()
for pkg in "${PACKAGES[@]}"; do
    if ! dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
        MISSING+=("$pkg")
    fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
    echo "Installing: ${MISSING[*]}"
    apt-get update -qq
    apt-get install -y "${MISSING[@]}"
else
    echo "All packages already installed"
fi

###############################################################################
# 2. Enable and start systemd services (idempotent)
###############################################################################
echo ""
echo "=== Enabling systemd services ==="

for svc in systemd-networkd systemd-resolved; do
    if systemctl is-active --quiet "$svc"; then
        echo "$svc is already running"
    else
        echo "Starting $svc..."
        systemctl enable --now "$svc"
    fi
done

###############################################################################
# 3. Enable IPv4 forwarding (idempotent)
###############################################################################
echo ""
echo "=== Configuring IPv4 forwarding ==="

if [ "$(cat /proc/sys/net/ipv4/ip_forward)" = "1" ]; then
    echo "IPv4 forwarding already enabled"
else
    echo "Enabling IPv4 forwarding..."
    sysctl -w net.ipv4.ip_forward=1
fi

# Make it persistent
if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf 2>/dev/null; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    echo "Made IPv4 forwarding persistent"
fi

###############################################################################
# 4. Create container bridge network (idempotent)
###############################################################################
echo ""
echo "=== Configuring container bridge network ==="

BRIDGE_NETDEV="/etc/systemd/network/${IIAB_BRIDGE}.netdev"
BRIDGE_NETWORK="/etc/systemd/network/${IIAB_BRIDGE}.network"

# Create netdev file
netdev_changed=false
if [ ! -f "$BRIDGE_NETDEV" ]; then
    echo "Creating bridge netdev config..."
    cat > "$BRIDGE_NETDEV" << EOF
[NetDev]
Name=${IIAB_BRIDGE}
Kind=bridge

[Bridge]
DefaultPVID=
VLANFiltering=false
EOF
    netdev_changed=true
else
    echo "Bridge netdev config already exists"
fi

# Create network file
network_changed=false
if [ ! -f "$BRIDGE_NETWORK" ]; then
    echo "Creating bridge network config..."
    cat > "$BRIDGE_NETWORK" << EOF
[Match]
Name=${IIAB_BRIDGE}

[Network]
Address=${IIAB_GW}/24
IPForward=yes
IPMasquerade=yes
EOF
    network_changed=true
else
    echo "Bridge network config already exists"
fi

# Restart systemd-networkd only if configs were changed
if $netdev_changed || $network_changed; then
    echo "Restarting systemd-networkd to apply bridge config..."
    systemctl restart systemd-networkd
else
    echo "Bridge config unchanged, skipping systemd-networkd restart"
fi

###############################################################################
# 5. Deploy nginx configuration (idempotent)
###############################################################################
echo ""
echo "=== Configuring nginx ==="

# Create directories
mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled /var/www/certbot

# Create a minimal nginx config (will be regenerated by nginx-gen.sh later)
NGINX_CONF="/etc/nginx/sites-available/iiab-demo.conf"
if [ ! -f "$NGINX_CONF" ]; then
    echo "Creating initial nginx config..."
    cat > "$NGINX_CONF" << 'EOF'
# Auto-generated by host-setup.sh
# This will be regenerated by democtl reload

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location / {
        return 404;
    }
}
EOF
else
    echo "Nginx config already exists"
fi

# Enable site (idempotent)
if [ ! -L "/etc/nginx/sites-enabled/iiab-demo.conf" ]; then
    echo "Enabling nginx site..."
    ln -sf /etc/nginx/sites-available/iiab-demo.conf /etc/nginx/sites-enabled/
else
    echo "Nginx site already enabled"
fi

# Remove default site (idempotent)
if [ -L "/etc/nginx/sites-enabled/default" ]; then
    echo "Removing default nginx site..."
    rm -f /etc/nginx/sites-enabled/default
else
    echo "Default nginx site already removed"
fi

# Enable and start nginx (idempotent)
if systemctl is-active --quiet nginx; then
    echo "nginx is already running"
else
    echo "Starting nginx..."
    systemctl enable --now nginx
fi

###############################################################################
# 6. Configure iptables for container NAT (idempotent)
###############################################################################
echo ""
echo "=== Configuring iptables for container NAT ==="

EXT_IF=$(ip route | grep default | awk '{print $5}' | head -n1)
if [ -z "$EXT_IF" ]; then
    echo "Warning: Could not detect external interface, skipping iptables" >&2
else
    setup_iptables_nat "$EXT_IF"

    # Add container-to-container isolation (applies to all current and future containers)
    # Called after NAT rules so ordering is correct in FORWARD chain
    add_container_isolation
fi

# Make iptables persistent
if ! command -v iptables-save >/dev/null 2>&1; then
    echo "Installing iptables-persistent..."
    apt-get install -y iptables-persistent
fi

mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4
echo "Iptables rules saved to /etc/iptables/rules.v4"

###############################################################################
# 7. Create required directories (idempotent)
###############################################################################
echo ""
echo "=== Creating required directories ==="

ensure_dirs /var/lib/machines /var/www/certbot

###############################################################################
# 8. Test nginx configuration
###############################################################################
echo ""
echo "=== Testing nginx configuration ==="

nginx_reload

echo ""
echo "=== Host setup complete! ==="
echo "Add demos with:"
echo "  make small medium large"
echo "  democtl add <name> --local-vars <path>"
