#!/usr/bin/env bash
# shellcheck disable=SC2016
# nginx-gen.sh - Dynamically generate nginx config from active demos
# Reads /var/lib/iiab-demos/active/*/config and produces nginx config
set -euo pipefail

STATE_DIR="/var/lib/iiab-demos"
ACTIVE_DIR="$STATE_DIR/active"
NGINX_CONF="/etc/nginx/sites-available/iiab-demo.conf"
CERTBOT_ROOT="/var/www/certbot"

# Sanitize a name into a valid nginx server_name / upstream-safe identifier
sanitize_subdomain() {
    local raw="$1"
    # Lowercase, strip anything except a-z 0-9 and hyphen
    local cleaned
    cleaned=$(echo "$raw" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')
    # Remove leading/trailing hyphens
    cleaned="${cleaned#-}"
    cleaned="${cleaned%-}"
    if [ -z "$cleaned" ]; then
        echo "demo"  # fallback
    else
        echo "$cleaned"
    fi
}

# Collect active demos into array
demo_names=()
for demo_dir in "$ACTIVE_DIR"/*/; do
    [ -d "$demo_dir" ] || continue
    dname=$(basename "$demo_dir")
    if [ ! -f "$demo_dir/config" ]; then
        echo "Warning: Demo '$dname' has no config file — skipping nginx generation" >&2
        continue
    fi
    demo_names+=("$dname")
done

if [ ${#demo_names[@]} -eq 0 ]; then
    echo "No active demos, skipping nginx generation"
    exit 0
fi

# Find wildcard domain first
fallback_domain="large.iiab.io"
for name in "${demo_names[@]}"; do
    # shellcheck source=/dev/null
    source "$ACTIVE_DIR/$name/config"
    if [ "${WILDCARD:-false}" = "true" ]; then
        fallback_domain="$(sanitize_subdomain "${SUBDOMAIN:-$name}").iiab.io"
        break
    fi
done

generate_nginx() {
    cat << 'HEADER'
# Auto-generated by democtl nginx-gen.sh
# DO NOT EDIT - changes will be overwritten
# Routes *.iiab.io subdomains to systemd-nspawn containers

HEADER

    # Collect subdomains for HTTP server
    all_server_names=""

    # Upstream blocks
    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        ip=$(cat "$ACTIVE_DIR/$name/ip")
        subdomain=$(sanitize_subdomain "${SUBDOMAIN:-$name}")
        upstream_name=$(echo "$name" | tr '-' '_')
        all_server_names="${all_server_names}${subdomain}.iiab.io "

        printf "upstream %s {\n    server %s:80;\n    keepalive 32;\n}\n\n" \
            "$upstream_name" "$ip"
    done

    # HTTP server - ACME challenges + redirect
    {
        printf '# HTTP server - serve ACME challenges + conditional redirect to HTTPS\n'
        printf 'server {\n'
        printf '    listen 80 default_server;\n'
        printf '    listen [::]:80 default_server;\n'
        printf '    server_name %s;\n\n' "$all_server_names"
        printf '    location /.well-known/acme-challenge/ {\n'
        printf '        root %s;\n' "$CERTBOT_ROOT"
        printf '    }\n\n'
        printf '    location / {\n'
    }

    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        subdomain=$(sanitize_subdomain "${SUBDOMAIN:-$name}")
        cert_path="/etc/letsencrypt/live/${subdomain}.iiab.io/fullchain.pem"
        upstream_name=$(echo "$name" | tr '-' '_')

        if [ -f "$cert_path" ]; then
            printf '        if ($host = "%s.iiab.io") {\n' "$subdomain"
            printf '            return 301 https://$host$request_uri;\n'
            printf '        }\n'
        else
            printf '        if ($host = "%s.iiab.io") {\n' "$subdomain"
            printf '            proxy_pass http://%s;\n' "$upstream_name"
            printf '            proxy_set_header Host $host;\n'
            printf '            proxy_set_header X-Real-IP $remote_addr;\n'
            printf '            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n'
            printf '            proxy_set_header X-Forwarded-Proto $scheme;\n'
            printf '            proxy_http_version 1.1;\n'
            printf '            proxy_set_header Upgrade $http_upgrade;\n'
            printf '            proxy_set_header Connection "upgrade";\n'
            printf '        }\n'
        fi
    done

    {
        printf '\n        return 404;\n'
        printf '    }\n'
        printf '}\n}\n\n'
        printf '# HTTP catch-all for other *.iiab.io\n'
        printf 'server {\n'
        printf '    listen 80;\n'
        printf '    listen [::]:80;\n'
        printf '    server_name *.iiab.io;\n\n'
        printf '    location /.well-known/acme-challenge/ {\n'
        printf '        root %s;\n' "$CERTBOT_ROOT"
        printf '    }\n\n'
        printf '    location / {\n'
        printf '        return 302 https://%s$request_uri;\n' "$fallback_domain"
        printf '    }\n'
        printf '}\n\n'
    }

    # HTTPS server blocks for each demo
    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        subdomain=$(sanitize_subdomain "${SUBDOMAIN:-$name}")
        upstream_name=$(echo "$name" | tr '-' '_')
        cert_path="/etc/letsencrypt/live/${subdomain}.iiab.io/fullchain.pem"

        if [ -f "$cert_path" ]; then
            printf '# HTTPS server for %s.iiab.io\n' "$subdomain"
            printf 'server {\n'
            printf '    listen 443 ssl http2;\n'
            printf '    listen [::]:443 ssl http2;\n'
            printf '    server_name %s.iiab.io;\n\n' "$subdomain"
            printf '    ssl_certificate %s;\n' "$cert_path"
            printf '    ssl_certificate_key /etc/letsencrypt/live/%s.iiab.io/privkey.pem;\n' "$subdomain"
            printf '    ssl_protocols TLSv1.2 TLSv1.3;\n'
            printf '    ssl_stapling on;\n'
            printf '    ssl_stapling_verify on;\n\n'
            printf '    location / {\n'
            printf '        proxy_pass http://%s;\n' "$upstream_name"
            printf '        proxy_set_header Host $host;\n'
            printf '        proxy_set_header X-Real-IP $remote_addr;\n'
            printf '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n'
            printf '        proxy_set_header X-Forwarded-Proto $scheme;\n'
            printf '        proxy_set_header X-Forwarded-Host $host;\n'
            printf '        proxy_http_version 1.1;\n'
            printf '        proxy_set_header Upgrade $http_upgrade;\n'
            printf '        proxy_set_header Connection "upgrade";\n'
            printf '    }\n'
            printf '}\n\n'
        else
            printf '# HTTPS server for %s.iiab.io (DISABLED - certificate not found)\n' "$subdomain"
            printf "# Run 'democtl certbot' to obtain certificates\n"
        fi
    done

    # Fallback server
    fallback_cert="/etc/letsencrypt/live/${fallback_domain}/fullchain.pem"
    if [ -f "$fallback_cert" ]; then
        printf '# Catch-all for any other *.iiab.io subdomains\n'
        printf 'server {\n'
        printf '    listen 443 ssl http2 default_server;\n'
        printf '    listen [::]:443 ssl http2 default_server;\n'
        printf '    server_name *.iiab.io;\n\n'
        printf '    ssl_certificate %s;\n' "$fallback_cert"
        printf '    ssl_certificate_key /etc/letsencrypt/live/%s.iiab.io/privkey.pem;\n' "$fallback_domain"
        printf '    ssl_protocols TLSv1.2 TLSv1.3;\n\n'
        printf '    return 302 https://%s$request_uri;\n' "$fallback_domain"
        printf '}\n'
    fi
}

generate_nginx > "$NGINX_CONF"

echo "Generated nginx config: $NGINX_CONF"

# Test and reload
if nginx -t 2>/dev/null; then
    systemctl reload nginx
    echo "Nginx reloaded successfully"
else
    echo "Warning: nginx config test failed, not reloading" >&2
    nginx -t >&2
    exit 1
fi
