#!/usr/bin/env bash
# shellcheck disable=SC2016
# nginx-gen.sh - Dynamically generate nginx config from active demos
# Reads /var/lib/iiab-demos/active/*/config and produces nginx config
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-iiab.sh disable=SC1091
source "$SCRIPT_DIR/lib-iiab.sh"

STATE_DIR="/var/lib/iiab-demos"
ACTIVE_DIR="$STATE_DIR/active"
NGINX_CONF="/etc/nginx/sites-available/iiab-demo.conf"
CERTBOT_ROOT="/var/www/certbot"

# Flock to prevent concurrent nginx config writes/reloads
NGINX_LOCK="/var/lib/iiab-demos/.nginx-gen.lock"
NGINX_LOCK_FD=202

acquire_nginx_lock() {
    eval "exec $NGINX_LOCK_FD>$NGINX_LOCK"
    if ! flock -w 30 "$NGINX_LOCK_FD"; then
        echo "Error: Could not acquire nginx generation lock -- another generation may be in progress" >&2
        exit 1
    fi
}

release_nginx_lock() {
    flock -u "$NGINX_LOCK_FD" 2>/dev/null || true
}

trap release_nginx_lock EXIT

# Acquire lock before generating config
acquire_nginx_lock

# Collect active demos into array
demo_names=()
for demo_dir in "$ACTIVE_DIR"/*/; do
    [ -d "$demo_dir" ] || continue
    dname=$(basename "$demo_dir")
    if [ ! -f "$demo_dir/config" ]; then
        echo "Warning: Demo '$dname' has no config file -- skipping nginx generation" >&2
        continue
    fi
    demo_names+=("$dname")
done

if [ ${#demo_names[@]} -eq 0 ]; then
    echo "No active demos, skipping nginx generation"
    exit 0
fi

# Find wildcard domain first
fallback_domain="large.iiab.io"
for name in "${demo_names[@]}"; do
    # shellcheck source=/dev/null
    source "$ACTIVE_DIR/$name/config"
    if [ "${WILDCARD:-false}" = "true" ]; then
        fallback_domain="$(sanitize_subdomain "${SUBDOMAIN:-$name}").iiab.io"
        break
    fi
done

generate_nginx() {
    cat << 'HEADER'
# Auto-generated by democtl nginx-gen.sh
# DO NOT EDIT - changes will be overwritten
# Routes *.iiab.io subdomains to systemd-nspawn containers

HEADER

    # Upstream blocks
    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        ip=$(cat "$ACTIVE_DIR/$name/ip")
        subdomain=$(sanitize_subdomain "${SUBDOMAIN:-$name}")
        upstream_name=$(echo "$name" | tr '-' '_')

        printf "upstream %s {\n    server %s:80;\n    keepalive 32;\n}\n\n" \
            "$upstream_name" "$ip"
    done

    # Fallback HTTP catch-all for *.iiab.io
    printf '# Fallback HTTP catch-all for *.iiab.io\n'
    printf 'server {\n'
    printf '    listen 80 default_server;\n'
    printf '    listen [::]:80 default_server;\n'
    printf '    server_name *.iiab.io;\n\n'
    printf '    location /.well-known/acme-challenge/ {\n'
    printf '        root %s;\n' "$CERTBOT_ROOT"
    printf '    }\n\n'
    printf '    location / {\n'
    printf '        return 302 https://%s$request_uri;\n' "$fallback_domain"
    printf '    }\n'
    printf '}\n\n'

    # HTTP server blocks -- one per demo (avoids if-in-location issues)
    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        subdomain=$(sanitize_subdomain "${SUBDOMAIN:-$name}")
        cert_path="/etc/letsencrypt/live/${subdomain}.iiab.io/fullchain.pem"
        upstream_name=$(echo "$name" | tr '-' '_')

        if [ -f "$cert_path" ]; then
            # HTTPS available -- redirect HTTP to HTTPS
            printf '# HTTP redirect for %s.iiab.io\n' "$subdomain"
            printf 'server {\n'
            printf '    listen 80;\n'
            printf '    listen [::]:80;\n'
            printf '    server_name %s.iiab.io;\n\n' "$subdomain"
            printf '    location /.well-known/acme-challenge/ {\n'
            printf '        root %s;\n' "$CERTBOT_ROOT"
            printf '    }\n\n'
            printf '    location / {\n'
            printf '        return 301 https://$host$request_uri;\n'
            printf '    }\n'
            printf '}\n\n'
        else
            # No HTTPS -- proxy to container
            printf '# HTTP proxy for %s.iiab.io\n' "$subdomain"
            printf 'server {\n'
            printf '    listen 80;\n'
            printf '    listen [::]:80;\n'
            printf '    server_name %s.iiab.io;\n\n' "$subdomain"
            printf '    location /.well-known/acme-challenge/ {\n'
            printf '        root %s;\n' "$CERTBOT_ROOT"
            printf '    }\n\n'
            printf '    location / {\n'
            printf '        proxy_pass http://%s;\n' "$upstream_name"
            printf '        proxy_set_header Host $host;\n'
            printf '        proxy_set_header X-Real-IP $remote_addr;\n'
            printf '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n'
            printf '        proxy_set_header X-Forwarded-Proto $scheme;\n'
            printf '        proxy_http_version 1.1;\n'
            printf '        proxy_set_header Upgrade $http_upgrade;\n'
            printf '        proxy_set_header Connection "upgrade";\n'
            printf '    }\n'
            printf '}\n\n'
        fi
    done

    # HTTPS server blocks for each demo
    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        subdomain=$(sanitize_subdomain "${SUBDOMAIN:-$name}")
        upstream_name=$(echo "$name" | tr '-' '_')
        cert_path="/etc/letsencrypt/live/${subdomain}.iiab.io/fullchain.pem"

        if [ -f "$cert_path" ]; then
            printf '# HTTPS server for %s.iiab.io\n' "$subdomain"
            printf 'server {\n'
            printf '    listen 443 ssl http2;\n'
            printf '    listen [::]:443 ssl http2;\n'
            printf '    server_name %s.iiab.io;\n\n' "$subdomain"
            printf '    ssl_certificate %s;\n' "$cert_path"
            printf '    ssl_certificate_key /etc/letsencrypt/live/%s.iiab.io/privkey.pem;\n' "$subdomain"
            printf '    ssl_protocols TLSv1.2 TLSv1.3;\n'
            printf '    ssl_stapling on;\n'
            printf '    ssl_stapling_verify on;\n\n'
            printf '    location / {\n'
            printf '        proxy_pass http://%s;\n' "$upstream_name"
            printf '        proxy_set_header Host $host;\n'
            printf '        proxy_set_header X-Real-IP $remote_addr;\n'
            printf '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n'
            printf '        proxy_set_header X-Forwarded-Proto $scheme;\n'
            printf '        proxy_set_header X-Forwarded-Host $host;\n'
            printf '        proxy_http_version 1.1;\n'
            printf '        proxy_set_header Upgrade $http_upgrade;\n'
            printf '        proxy_set_header Connection "upgrade";\n'
            printf '    }\n'
            printf '}\n\n'
        else
            printf '# HTTPS server for %s.iiab.io (DISABLED - certificate not found)\n' "$subdomain"
            printf "# Run 'democtl certbot' to obtain certificates\n"
        fi
    done

    # Fallback server
    fallback_cert="/etc/letsencrypt/live/${fallback_domain}/fullchain.pem"
    if [ -f "$fallback_cert" ]; then
        printf '# Catch-all for any other *.iiab.io subdomains\n'
        printf 'server {\n'
        printf '    listen 443 ssl http2 default_server;\n'
        printf '    listen [::]:443 ssl http2 default_server;\n'
        printf '    server_name *.iiab.io;\n\n'
        printf '    ssl_certificate %s;\n' "$fallback_cert"
        printf '    ssl_certificate_key /etc/letsencrypt/live/%s/privkey.pem;\n' "$fallback_domain"
        printf '    ssl_protocols TLSv1.2 TLSv1.3;\n\n'
        printf '    return 302 https://%s$request_uri;\n' "$fallback_domain"
        printf '}\n'
    fi
}

generate_nginx > "$NGINX_CONF"

echo "Generated nginx config: $NGINX_CONF"

# Test and reload
nginx_reload
