#!/usr/bin/env bash
# nginx-gen.sh - Dynamically generate nginx config from active demos
# Reads /var/lib/iiab-demos/active/*/config and produces nginx config
set -euo pipefail

STATE_DIR="/var/lib/iiab-demos"
ACTIVE_DIR="$STATE_DIR/active"
NGINX_CONF="/etc/nginx/sites-available/iiab-demo.conf"
CERTBOT_ROOT="/var/www/certbot"

# Collect active demos into array
demo_names=()
for demo_dir in "$ACTIVE_DIR"/*/; do
    [ -d "$demo_dir" ] || continue
    dname=$(basename "$demo_dir")
    [ -f "$demo_dir/config" ] || continue
    demo_names+=("$dname")
done

if [ ${#demo_names[@]} -eq 0 ]; then
    echo "No active demos, skipping nginx generation"
    exit 0
fi

# Find fallback domain first
fallback_domain="large.iiab.io"
for name in "${demo_names[@]}"; do
    # shellcheck source=/dev/null
    source "$ACTIVE_DIR/$name/config"
    if [ "${FALLBACK:-false}" = "true" ]; then
        fallback_domain="${SUBDOMAIN:-$name}.iiab.io"
        break
    fi
done

generate_nginx() {
    cat << 'HEADER'
# Auto-generated by democtl nginx-gen.sh
# DO NOT EDIT - changes will be overwritten
# Routes *.iiab.io subdomains to systemd-nspawn containers

HEADER

    # Collect subdomains for HTTP server
    all_server_names=""

    # Upstream blocks
    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        ip=$(cat "$ACTIVE_DIR/$name/ip")
        subdomain="${SUBDOMAIN:-$name}"
        upstream_name=$(echo "$name" | tr '-' '_')
        all_server_names="${all_server_names}${subdomain}.iiab.io "

        cat << EOF
upstream ${upstream_name} {
    server ${ip}:80;
    keepalive 32;
}

EOF
    done

    # HTTP server - ACME challenges + redirect
    cat << EOF
# HTTP server - serve ACME challenges + redirect to HTTPS
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ${all_server_names};

    location /.well-known/acme-challenge/ {
        root ${CERTBOT_ROOT};
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

# HTTP catch-all for other *.iiab.io
server {
    listen 80;
    listen [::]:80;
    server_name *.iiab.io;

    location /.well-known/acme-challenge/ {
        root ${CERTBOT_ROOT};
    }

    return 302 https://${fallback_domain}\$request_uri;
}

EOF

    # HTTPS server blocks for each demo
    for name in "${demo_names[@]}"; do
        # shellcheck source=/dev/null
        source "$ACTIVE_DIR/$name/config"
        subdomain="${SUBDOMAIN:-$name}"
        upstream_name=$(echo "$name" | tr '-' '_')

        cat << EOF
# HTTPS server for ${subdomain}.iiab.io
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${subdomain}.iiab.io;

    ssl_certificate /etc/letsencrypt/live/${subdomain}.iiab.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${subdomain}.iiab.io/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_stapling on;
    ssl_stapling_verify on;

    location / {
        proxy_pass http://${upstream_name};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

EOF
    done

    # Fallback server
    cat << EOF
# Catch-all for any other *.iiab.io subdomains
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name *.iiab.io;

    ssl_certificate /etc/letsencrypt/live/${fallback_domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${fallback_domain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 302 https://${fallback_domain}\$request_uri;
}
EOF
}

generate_nginx > "$NGINX_CONF"

echo "Generated nginx config: $NGINX_CONF"

# Test and reload
if nginx -t 2>/dev/null; then
    systemctl reload nginx
    echo "Nginx reloaded successfully"
else
    echo "Warning: nginx config test failed, not reloading" >&2
    nginx -t >&2
    exit 1
fi
